# config/services/event_listener.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Users\EventListener\UserEntityEventListener:
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }

    App\Users\EventListener\UserRegisteredEventListener:
            tags:
                - { name: kernel.event_listener, event: user.registered }

    App\Translation\EventListener\LocaleListener:
            tags:
                - { name: kernel.event_subscriber }

    App\Translation\EventListener\TranslatedEntityResponseListener:
            tags:
                - { name: kernel.event_subscriber, event: kernel.view }