services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    app.async.movie_sync_processor:
        class: App\Movies\EventListener\MovieSyncProcessor
        tags:
            - { name: enqueue.client.processor }