services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Movies\EventListener\MovieSyncProcessor:
        tags:
            - { name: enqueue.client.processor }

    App\Movies\EventListener\WatchedMovieProcessor:
        tags:
            - { name: enqueue.client.processor }

    App\Movies\EventListener\MovieTranslationsProcessor:
        tags:
            - { name: enqueue.client.processor }

    App\Movies\EventListener\SimilarMoviesProcessor:
        tags:
            - { name: enqueue.client.processor }

    App\Movies\EventListener\AddSimilarMoviesProcessor:
        tags:
            - { name: enqueue.client.processor }

    App\Movies\EventListener\AddRecommendationProcessor:
        tags:
            - { name: enqueue.client.processor }