# config/services/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Service\LocaleService:
        $locale: '%locale%'
        $locales: '%locales%'