# config/services/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GuzzleHttp\Client: ~
    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

    App\Service\LocaleService:
        $locale: '%locale%'
        $locales: '%locales%'