security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        db_user_provider:
            entity:
                class: App\Entity\User
    firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
    encoders:
        App\Entity\User:
            algorithm: bcrypt