security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        db_user_provider:
            id: App\Users\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api
            stateless: true
            anonymous: true
            logout: ~
            provider: db_user_provider
            guard:
              authenticators:
                - App\Users\Security\TokenAuthenticator
    encoders:
        App\Users\Entity\User:
            algorithm: bcrypt