language: php

php:
  - 7.2

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - composer install
  - ./bin/composer install
  - cp .env.dist .env.test

env:
  - DATABASE_URL="pgsql://my_art_lib:my_art_lib@localhost/my_art_lib"

before_script:
  - psql -c "CREATE DATABASE my_art_lib;" -U postgres
  - psql -c "CREATE USER my_art_lib WITH PASSWORD 'my_art_lib';" -U postgres

script:
  - ./bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover