language: php

php:
  - 7.2

install:
  - composer install

script:
  - ./bin/phpunit tests/Unit/* -- --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover