version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: svbackend/my-art-lib
    ports:
      - 8000:80
    volumes:
      - .:/srv/app
    links:
      - postgres
      - redis
    environment:
          DB_HOST: postgres
          DB_DATABASE: my_art_lib
          DB_USERNAME: my_art_lib
          DB_PASSWORD: my_art_lib
          REDIS_HOST: redis
          SESSION_DRIVER: redis
          CACHE_DRIVER: redis
  postgres:
      image: postgres:9.6
      ports:
        - 15432:5432
      environment:
        POSTGRES_DB: my_art_lib
        POSTGRES_USER: my_art_lib
        POSTGRES_PASSWORD: my_art_lib
      volumes:
        - /postgres-data:/var/lib/postgresql/data
  redis:
      image: redis:4.0-alpine
      ports:
        - 16379:6379
