api:
    resource: routes/api.yaml
    prefix: /api
    type: rest

confirm_email:
    path: /api/doc
    methods: GET

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }