users:
    resource: ../src/Users/Controller
    type: annotation
genres:
    resource: ../src/Genres/Controller
    type: annotation

confirm_email:
    path: /api/confirmEmail
    methods: GET

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }