guests:
    resource: ../src/Guests/Controller
    type: annotation
users:
    resource: ../src/Users/Controller
    type: annotation
genres:
    resource: ../src/Genres/Controller
    type: annotation
movies:
    resource: ../src/Movies/Controller
    type: annotation
images:
    resource: ../src/Images/Controller
    type: annotation

# Confirm email route used for generating url to confirmation url in email letters
confirm_email:
    path: /api/confirmEmail
    methods: GET