# config/services.yaml
parameters:
    appName: '%env(APP_NAME)%'
    appFrontendUrl: '%env(APP_FRONTEND_URL)%'
    locale: 'en'
    locales: ["en", "ru", "uk", "pl"]
    router.request_context.host: 127.0.0.1/
    router.request_context.scheme: https
    router.request_context.base_url: '/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/**/{EventListener,Entity,DTO,Migrations,Tests,Kernel.php}'

    App\Service\LocaleService:
        arguments:
            $defaultLocale: "%locale%"
            $locales: "%locales%"

    App\Movies\Service\ImdbIdLoaderService:
        public: true

    _instanceof:
        App\Controller\ControllerInterface:
            tags: ['controller.service_arguments']

imports:
    - { resource: services/*.yaml }